## ---------------------------
##
## Script name: Antigenic Cartography for Norovirus
##
## Purpose of script: This script takes coordinate data generated by racmacs from blockade titer data 
## found in XX.
##
## Author: F.A.T.Boshier
##
## Date Created: 2021-10-21
##
## Email: f.boshier@ucl.ac.uk
##
## ---------------------------
##
## Notes: Script takes results from RACMACs and makes antigenic cartography plots for paper.
##   
##
## ---------------------------


## ---------------------------

## load up the packages we will need:  (uncomment as required)
require(Racmacs)
require(ggplot2)
require(tidyverse)
require(knitr)
require(RColorBrewer)
require(wesanderson)
require(viridis)
require(pdist)
require(kableExtra)
require(patchwork)
require(rstatix)
require(rgl)
require(plotly)

require(htmlwidgets)

## ---------------------------

## SURVEILLANCE SERA

## ---------------------------

## ---------------------------

## read in maps generated by racmacs


map.sur<- read.acmap("./Surveillance-Sera-2D.ace")
map3D.sur<- read.acmap("./Surveillance-Sera-3D.ace")

antigen.list<-c("Hong_Kong_2019","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008")

## ---------------------------


## ---------------------------

## plot 2D antigenic space - figures 4 D-F


# Generating antigen dataframe for plotting

ag.plot<-data.frame("label"=antigen.list,"type"="antigen",
                    "x"=agCoords(map.sur, 1)[,1],
                    "y"=agCoords(map.sur, 1)[,2])

# Generating antigen dataframe for plotting, including calculating the mean of the sera


sr.plot<-rbind(data.frame("label"="child.1214","type"="serum",
                          "x"=srCoords(map.sur,1)[20:53,1],
                          "y"=srCoords(map.sur,1)[20:53,2]),
               data.frame("label"="adult.1214","type"="serum",
                          "x"=srCoords(map.sur,1)[54:78,1],
                          "y"=srCoords(map.sur,1)[54:78,2]),
               data.frame("label"="adult.1719","type"="serum",
                          "x"=srCoords(map.sur,1)[1:19,1],
                          "y"=srCoords(map.sur,1)[1:19,2]),
               data.frame("label"="child.1819","type"="serum",
                          "x"=srCoords(map.sur,1)[79:95,1],
                          "y"=srCoords(map.sur,1)[79:95,2])
)

sr.plot<-rbind(sr.plot,
               reshape::cast(reshape2::melt(sr.plot), label ~ variable , mean, margins=TRUE) %>%
                 select(label,x,y) %>%
                 filter(label!="(all)") %>% 
                 mutate(type="serum") %>% 
                 mutate(label=case_when(
                   label=="child.1214" ~ "ctr.child1214",
                   label=="adult.1214" ~ "ctr.adult1214",
                   label=="adult.1719" ~ "ctr.adult1719",
                   label=="child.1819" ~ "ctr.child1819"
                 )))

# Merging dataframe of antigen and sera for plotting


ag.sr.plot<-rbind(ag.plot,sr.plot)%>%
  mutate(label=factor(label,levels=c("child.1214","adult.1214","adult.1719","child.1819","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719","ctr.child1819"))) %>%
  mutate(stroke=c(rep(0.5,100),rep(1.1,4)))

# write.csv(ag.sr.plot %>% select(-stroke),"2D-antigenic-cartography-coordinates.csv",
#           quote=FALSE,row.names=FALSE)
# 

# Generating aesthetic variables for plotting
label_order<-c("child.1214","adult.1214","adult.1719","child.1819","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719","ctr.child1819")
legend_order<-c("2013-2014 Children's Sera ","2013-2014 Adults' Sera ","2017-2019 Adults' Sera","2018-2019 Children's Sera",
                "Sydney 2012","Den_Haag 2006","Den Haag 2017","Osaka 2007","Hong Kong 2019","Mean 2013-2014 Children's Sera","Mean 2013-2014 Adults' Sera","Mean 2017-2019 Adults' Sera","Mean 2018-2019 Children's Sera")
coord.min=floor(min(c(ag.sr.plot$x,ag.sr.plot$y)))-1
coord.max=ceiling(max(c(ag.sr.plot$x,ag.sr.plot$y)))+1

# begin plotting

all.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label,stroke=stroke),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum"),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="adult.1214"),aes(group="adult.1214",fill=label),color=NA,alpha=1/4)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="adult.1719"),aes(group="adult.1719",fill=label),color=NA,alpha=1/4)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="child.1214"),aes(group="child.1214",fill=label),color=NA,alpha=1/4)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="child.1819"),aes(group="child.1819",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,4),15,16,17,18,25,9,10,12,13))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod",rep("black",5),rep("grey30",4)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod"),
                    breaks=label_order[1:4],
                    label=legend_order[1:4],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank(),
                   legend.text=element_text(size=12))+
  coord_fixed()+guides(color=guide_legend(override.aes = list(stroke=c(rep(0.5,9),rep(1,4)),size=c(rep(3,4),rep(5,5),rep(3,4)))))+ggtitle("All Sera")

all.p

child.1214.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label %in% c("child.1214","ctr.child1214")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="child.1214"),aes(group="child.1214",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,4),15,16,17,18,25,9,10,12,13))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod",rep("black",5),rep("grey30",4)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod"),
                    breaks=label_order[1:4],
                    label=legend_order[1:4],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+
  ggtitle("2013-2014 Children's Sera")
child.1214.p


adult.1214.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label%in% c("adult.1214","ctr.adult1214")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="adult.1214"),aes(group="adult.1214",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,4),15,16,17,18,25,9,10,12,13))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod",rep("black",5),rep("grey30",4)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod"),
                    breaks=label_order[1:4],
                    label=legend_order[1:4],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+
  ggtitle("2013-2014 Adults' Sera")
adult.1214.p



adult.1719.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label %in% c("adult.1719","ctr.adult1719")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="adult.1719"),aes(group="adult.1719",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,4),15,16,17,18,25,9,10,12,13))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod",rep("black",5),rep("grey30",4)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod"),
                    breaks=label_order[1:4],
                    label=legend_order[1:4],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+
  ggtitle("2017-2019 Adults Sera")


adult.1719.p


child.1819.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label %in% c("child.1819","ctr.child1819")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="child.1819"),aes(group="child.1819",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,4),15,16,17,18,25,9,10,12,13))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod",rep("black",5),rep("grey30",4)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod"),
                    breaks=label_order[1:4],
                    label=legend_order[1:4],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+
  ggtitle("2018-2019 Children's Sera")


child.1819.p

mylegend<-ggpubr::get_legend(all.p)
child.1214.p<-child.1214.p+theme(legend.position="none")
adult.1214.p<-adult.1214.p+theme(legend.position="none")
adult.1719.p<-adult.1719.p+theme(legend.position="none")
child.1819.p<-child.1819.p+theme(legend.position="none")

child.1214.p+adult.1214.p + adult.1719.p+child.1819.p +ggpubr::as_ggplot(mylegend)+ 
  plot_layout(nrow = 1)

ggsave("figure4-etog.png",width=20,height=15)

fig7A<-all.p+ggtitle("Surveillance Sera")
ggsave("figureS7A.png",fig7A,width=12,height=6)




## ---------------------------

## Comparing 2D map.sur and 3D regression of normalised titer data

lm_eqn <- function(df){
  m <- lm(dij ~ Dij, df);
  eq <- substitute(italic(R)^2~"="~r2, 
                   list(r2 = format(summary(m)$r.squared, digits = 3)))
  as.character(as.expression(eq));
}

corr.dat.2D<-data.frame("dij"=as.vector(as.matrix(pdist(agBaseCoords(map.sur),srBaseCoords(map.sur)))),"Dij"=as.numeric(as.vector(tableDistances(map.sur))))

corr.plot.2D<-ggplot(corr.dat.2D,aes(x=Dij,y=dij))+geom_point()+
  theme_bw()+
  scale_x_continuous(expand=c(0,0),limits=c(0,9),breaks=(0:9))+
  scale_y_continuous(expand=c(0,0),limits=c(0,6))+
  coord_fixed()+geom_text(x=7,y=1,label=lm_eqn(corr.dat.2D),parse=TRUE)+
  ggtitle("2D Antigenic Map")+xlab(bquote(D[ij]))+ylab(bquote(d[ij]))


corr.dat.3D<-data.frame("dij"=as.vector(as.matrix(pdist(agBaseCoords(map3D.sur),srBaseCoords(map3D.sur)))),"Dij"=as.numeric(as.vector(tableDistances(map3D.sur))))

corr.plot.3D<-ggplot(corr.dat.3D,aes(x=Dij,y=dij))+geom_point()+
  theme_bw()+
  scale_x_continuous(expand=c(0,0),limits=c(0,9),breaks=(0:9))+
  scale_y_continuous(expand=c(0,0),limits=c(0,6))+
  coord_fixed()+geom_text(x=7,y=1,label=lm_eqn(corr.dat.3D),parse=TRUE)+
  ggtitle("3D Antigenic Map")+xlab(bquote(D[ij]))+ylab(bquote(d[ij]))

corr.plot.2D+corr.plot.3D

ggsave("figS9A.png",corr.plot.2D+corr.plot.3D)

## ---------------------------

## ---------------------------

## independent sera-analysis

map.child1214<-read.acmap("all-sera-wt-2D.child1214.ace")


ag.plot<-data.frame("label"=antigen.list,"type"="antigen",
                    "x"=agCoords(map.child1214, 1)[,1],
                    "y"=agCoords(map.child1214, 1)[,2])

# Generating antigen dataframe for plotting, including calculating the mean of the sera


sr.plot<-data.frame("label"="child.1214","type"="serum",
                    "x"=srCoords(map.child1214,1)[,1],
                    "y"=srCoords(map.child1214,1)[,2])

sr.plot<-rbind(sr.plot,
               reshape::cast(reshape2::melt(sr.plot), label ~ variable , mean, margins=TRUE) %>%
                 select(label,x,y) %>%
                 filter(label!="(all)") %>% 
                 mutate(type="serum") %>% 
                 mutate(label=case_when(
                   label=="child.1214" ~ "ctr.child1214"
                 )))

# Merging dataframe of antigen and sera for plotting



ag.sr.plot<-rbind(ag.plot,sr.plot)%>%
  mutate(label=factor(label,levels=c("child.1214","adult.1214","adult.1719","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719"))) %>%
  mutate(stroke=c(rep(0.5,37),rep(1.1,3)))

# Generating aesthetic variables for plotting
label_order<-c("child.1214","adult.1214","adult.1719","child.1819","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719","ctr.child1819")
legend_order<-c("2013-2014 Children's Sera ","2013-2014 Adults' Sera ","2017-2019 Adults' Sera","2017-2018 Children's Sera",
                "Sydney 2012","Den_Haag 2006","Den Haag 2017","Osaka 2007","Hong Kong 2019","Mean 2013-2014 Children's Sera","Mean 2013-2014 Adults' Sera","Mean 2017-2019 Adults' Sera","Mean 2018-2019 Children's Sera")
coord.min=floor(min(c(ag.sr.plot$x,ag.sr.plot$y)))-1
coord.max=ceiling(max(c(ag.sr.plot$x,ag.sr.plot$y)))+1

# begin plotting

all.p1<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label,stroke=stroke),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum"),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="child.1214"),aes(group="child.1214",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,4),15,16,17,18,25,rep(10,4)))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod",rep("black",5),rep("grey30",4)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod"),
                    breaks=label_order[1:4],
                    label=legend_order[1:4],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+guides(color=guide_legend(override.aes = list(stroke=c(rep(0.5,6),rep(1,1)),size=c(rep(3,1),rep(5,5),rep(3,1)))))+
  ggtitle("2013-2014 Children's Sera")




# Generating antigen dataframe for plotting

map.adult1214<-read.acmap("all-sera-wt-2D.adult1214.ace")


ag.plot<-data.frame("label"=antigen.list,"type"="antigen",
                    "x"=agCoords(map.adult1214, 1)[,1],
                    "y"=agCoords(map.adult1214, 1)[,2])

# Generating antigen dataframe for plotting, including calculating the mean of the sera


sr.plot<-data.frame("label"="adult.1214","type"="serum",
                    "x"=srCoords(map.adult1214,1)[,1],
                    "y"=srCoords(map.adult1214,1)[,2])

sr.plot<-rbind(sr.plot,
               reshape::cast(reshape2::melt(sr.plot), label ~ variable , mean, margins=TRUE) %>%
                 select(label,x,y) %>%
                 filter(label!="(all)") %>% 
                 mutate(type="serum") %>% 
                 mutate(label=case_when(
                   label=="adult.1214" ~ "ctr.adult1214"
                 )))

# Merging dataframe of antigen and sera for plotting



ag.sr.plot<-rbind(ag.plot,sr.plot)%>%
  mutate(label=factor(label,levels=c("child.1214","adult.1214","adult.1719","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719"))) %>%
  mutate(stroke=c(rep(0.5,28),rep(1.1,3)))

ag.sr.plot$x<--ag.sr.plot$x
ag.sr.plot$y<--ag.sr.plot$y
# Generating aesthetic variables for plotting
label_order<-c("child.1214","adult.1214","adult.1719","child.1819","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719","ctr.child1819")
legend_order<-c("2013-2014 Children's Sera ","2013-2014 Adults' Sera ","2017-2019 Adults' Sera","2017-2018 Children's Sera",
                "Sydney 2012","Den Haag 2006","Den Haag 2017","Osaka 2007","Hong Kong 2019","Mean 2013-2014 Children's Sera","Mean 2013-2014 Adults' Sera","Mean 2017-2019 Adults' Sera","Mean 2018-2019 Children's Sera")
# 
# coord.min=floor(min(c(ag.sr.plot$x,ag.sr.plot$y)))-1
# coord.max=ceiling(max(c(ag.sr.plot$x,ag.sr.plot$y)))+1

# begin plotting

all.p2<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label,stroke=stroke),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum"),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="adult.1214"),aes(group="adult.1214",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,4),15,16,17,18,25,rep(10,4)))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),rep("grey30",4)))+
  scale_fill_manual(values=c("darkolivegreen4"),
                    breaks=label_order[2:2],
                    label=legend_order[2:2],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+guides(color=guide_legend(override.aes = list(stroke=c(rep(0.5,6),rep(1,1)),size=c(rep(3,1),rep(5,5),rep(3,1)))))+
  ggtitle("2012-2014 Adults' Sera")




# Generating antigen dataframe for plotting

map.adult1719<-read.acmap("all-sera-wt-2D.adult1719.ace")


ag.plot<-data.frame("label"=antigen.list,"type"="antigen",
                    "x"=agCoords(map.adult1719, 1)[,1],
                    "y"=agCoords(map.adult1719, 1)[,2])

# Generating antigen dataframe for plotting, including calculating the mean of the sera


sr.plot<-data.frame("label"="adult.1719","type"="serum",
                    "x"=srCoords(map.adult1719,1)[,1],
                    "y"=srCoords(map.adult1719,1)[,2])

sr.plot<-rbind(sr.plot,
               reshape::cast(reshape2::melt(sr.plot), label ~ variable , mean, margins=TRUE) %>%
                 select(label,x,y) %>%
                 filter(label!="(all)") %>% 
                 mutate(type="serum") %>% 
                 mutate(label=case_when(
                   label=="adult.1719" ~ "ctr.adult1719"
                 )))

# Merging dataframe of antigen and sera for plotting



ag.sr.plot<-rbind(ag.plot,sr.plot)%>%
  mutate(label=factor(label,levels=c("child.1214","adult.1214","adult.1719","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719"))) %>%
  mutate(stroke=c(rep(0.5,24),rep(1.1,1)))


ag.sr.plot$x<--ag.sr.plot$x
ag.sr.plot$y<--ag.sr.plot$y
# Generating aesthetic variables for plotting
label_order<-c("child.1214","adult.1214","adult.1719","child.1819","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719","ctr.child1819")
legend_order<-c("2013-2014 Children's Sera ","2013-2014 Adults' Sera ","2017-2019 Adults' Sera","2017-2018 Children's Sera",
                "Sydney 2012","Den Haag 2006","Den Haag 2017","Osaka 2007","Hong Kong 2019","Mean 2013-2014 Children's Sera","Mean 2013-2014 Adults' Sera","Mean 2017-2019 Adults' Sera","Mean 2018-2019 Children's Sera")
# coord.min=floor(min(c(ag.sr.plot$x,ag.sr.plot$y)))-1
# coord.max=ceiling(max(c(ag.sr.plot$x,ag.sr.plot$y)))+1

# begin plotting

all.p3<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label,stroke=stroke),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum"),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="adult.1719"),aes(group="adult.1719",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,4),15,16,17,18,25,rep(10,4)))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod",rep("black",5),rep("grey30",4)))+
  scale_fill_manual(values=c("darkorchid3"),
                    breaks=label_order[3:3],
                    label=legend_order[3:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+guides(color=guide_legend(override.aes = list(stroke=c(rep(0.5,6),rep(1,1)),size=c(rep(3,1),rep(5,5),rep(3,1)))))+
  ggtitle("2017-2019 Adults' Sera")



# Generating antigen dataframe for plotting

map.child1819<-read.acmap("all-sera-wt-2D.child1819.ace")


ag.plot<-data.frame("label"=antigen.list,"type"="antigen",
                    "x"=agCoords(map.child1819, 1)[,1],
                    "y"=agCoords(map.child1819, 1)[,2])

# Generating antigen dataframe for plotting, including calculating the mean of the sera


sr.plot<-data.frame("label"="child.1819","type"="serum",
                    "x"=srCoords(map.child1819,1)[,1],
                    "y"=srCoords(map.child1819,1)[,2])

sr.plot<-rbind(sr.plot,
               reshape::cast(reshape2::melt(sr.plot), label ~ variable , mean, margins=TRUE) %>%
                 select(label,x,y) %>%
                 filter(label!="(all)") %>% 
                 mutate(type="serum") %>% 
                 mutate(label=case_when(
                   label=="child.1819" ~ "ctr.child1819"
                 )))

# Merging dataframe of antigen and sera for plotting





ag.sr.plot<-rbind(ag.plot,sr.plot)%>%
  mutate(label=factor(label,levels=c("child.1214","adult.1214","adult.1719","child.1819","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719","ctr.child1819"))) %>%
  mutate(stroke=c(rep(0.5,19),rep(1.1,4)))


ag.sr.plot$x<--ag.sr.plot$x
ag.sr.plot$y<--ag.sr.plot$y
# Generating aesthetic variables for plotting
label_order<-c("child.1214","adult.1214","adult.1719","child.1819","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719","ctr.child1819")
legend_order<-c("2013-2014 Children's Sera ","2012-2014 Adults' Sera ","2017-2019 Adults' Sera","2018-2018 Children's Sera",
                "Sydney 2012","Den_Haag 2006","Den Haag","Osaka 2007","Hong Kong 2019","Mean 2013-2014 Children's Sera","Mean 2012-2014 Adults' Sera","Mean 2017-2019 Adults' Sera","Mean 2018-2019 Children's Sera")
coord.min=floor(min(c(ag.sr.plot$x,ag.sr.plot$y)))-1
coord.max=ceiling(max(c(ag.sr.plot$x,ag.sr.plot$y)))+1

# begin plotting

all.p4<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label %in% c("child.1819","ctr.child1819")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="child.1819"),aes(group="child.1819",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,4),15,16,17,18,25,rep(10,4)))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod",rep("black",5),rep("grey30",4)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3","goldenrod"),
                    breaks=label_order[1:4],
                    label=legend_order[1:4],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+
  ggtitle("2018-2019 Children's Sera")



all.p1<-all.p1+theme(legend.position="none")
all.p2<-all.p2+theme(legend.position="none")
all.p3<-all.p3+theme(legend.position="none")
all.p4<-all.p4+theme(legend.position="none")


figS8A<-all.p1+all.p2+all.p3+all.p4+ggpubr::as_ggplot(mylegend)+ 
  plot_layout(nrow = 1)

ggsave("figS8A.png",figS8A,width=22.5,height=12)



## ---------------------------

## OUTBREAK SERA

## ---------------------------


## ---------------------------

## read in maps generated by racmacs


map.out<- read.acmap("./Outbreak-Sera-2D.ace")
map3d.out<- read.acmap("./Outbreak-Sera-3D.ace")

antigen.list.out<-c("GII.4.1997","GII.4.2002","GII.4.2006","GII.4.2009","GII.4.2012")
sera.list.out<-c("pre.FH_OB693sample#72","pre.FH_OB693sample#73","pre.FH_OB693sample#74",
                 "pre.FH_OB693sample#75","pre.FH_OB693sample#76","pre.FH_OB693sample#77",
                 "pre.FH_OB516sample#78","pre.FH_OB516sample#79","pre.FH_OB516sample#80",
                 "pre.FH_OB516sample#81","pre.FH_OB441sample#83","pre.FH_OB441sample#85",
                 "pre.FH_OB345sample#86","pre.FH_OB345sample#87","pre.FH_OB336sample#89",
                 "pre.FH_OB336sample#90","pre.FH_OB336sample#91","pre.FH_OB336sample#92",
                 "pre.FH_OB336sample#93","pre.FH_OB336sample#94","pre.FH_OB146sample#95",
                 "pre.FH_OB146sample#96","pre.FH_OB146sample#99","pre.FH_OB145sample#100",
                 "pre.FH_OB145sample#101","pre.FH_OB145sample#102","pre.FH_OB145sample#103",
                 "DH_OB2010-129sample#24","DH_OB2010-129sample#25","DH_OB2010-129sample#26",
                 "DH_OB2010-129sample#27","DH_OB2010-129sample#28","DH_OB2011-061sample#35",
                 "DH_OB2011-061sample#36","DH_OB2011-061sample#37","DH_OB2011-2176sample#38",
                 "DH_OB2011-2176sample#39","DH_OB1316sample#67","DH_OB1316sample#68",
                 "DH_OB1316sample#70","DH_OB1316sample#71","SY_OB2014-3217sample#50",
                 "SY_OB2014-3217sample#51","SY_OB2014-3217sample#52","SY_OB2014-3217sample#54",
                 "SY_OB2014-3217sample#55","SY_OB2014-3189sample#56","SY_OB2012-2458sample#58",
                 "SY_OB2012-2458sample#59","SY_OB2012-2458sample#60","SY_OB2012-2502sample#61",
                 "SY_OB2014-3243sample#62","SY_OB2014-3243sample#63","SY_OB2014-3243sample#64")
## ---------------------------

## plot 2D antigenic space - figures 4 D-F


# Generating antigen dataframe for plotting
# Generating antigen dataframe for plotting

ag.plot<-data.frame("label"=antigen.list.out,"type"="antigen",
                    "x"=agCoords(map.out, 1)[,1],
                    "y"=agCoords(map.out, 1)[,2])

# Generating antigen dataframe for plotting, including calculating the mean of the sera


sr.plot<-rbind(data.frame("label"=strsplit(sera.list.out,"_") %>% map_chr(`[`,1),"type"="serum",
                          "x"=srCoords(map.out,1)[,1],
                          "y"=srCoords(map.out,1)[,2])
)

sr.plot<-rbind(sr.plot,
               reshape::cast(reshape2::melt(sr.plot), label ~ variable , mean, margins=TRUE) %>%
                 select(label,x,y) %>%
                 filter(label!="(all)") %>% 
                 mutate(type="serum") %>% 
                 mutate(label=case_when(
                   label=="pre.FH" ~ "ctr.pre.FH",
                   label=="DH" ~ "ctr.DH",
                   label=="SY" ~ "ctr.SY"
                 )))

# Merging dataframe of antigen and sera for plotting



ag.sr.plot<-rbind(ag.plot,sr.plot)%>%
  mutate(label=factor(label,levels=c("pre.FH","DH","SY",antigen.list.out,"ctr.pre.FH","ctr.DH","ctr.SY"))) %>%
  mutate(stroke=c(rep(0.5,nrow(ag.plot)+nrow(sr.plot)-3),rep(1.1,3)))


# Generating aesthetic variables for plotting
label_order<-c("pre.FH","DH","SY",antigen.list.out,"ctr.pre.FH","ctr.DH","ctr.SY")
legend_order<-c("pre-Farmington Hills Sera","Den Haag Sera ","Sydney Sera","US95/95","Farmington Hills 2002",
                "Den Haag 2006","New Orleans 2009","Sydney 2012","Mean pre-Farmington Hills Sera","Den Haag Sera","Sydney Sera")
coord.min=floor(min(c(ag.sr.plot$x,ag.sr.plot$y)))-1
coord.max=ceiling(max(c(ag.sr.plot$x,ag.sr.plot$y)))+1

# begin plotting

all.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label,stroke=stroke),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum"),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="pre.FH"),aes(group="pre.FH",fill=label), expand=0.1,color=NA,alpha=1/4)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="DH"),aes(group="DH",fill=label), expand=0.1,color=NA,alpha=1/4)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="SY"),aes(group="SY",fill=label), expand=0.1,color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,3),15,16,17,18,25,9,10,12))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),rep("grey30",3)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3"),
                    breaks=label_order[1:3],
                    label=legend_order[1:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+guides(color=guide_legend(override.aes = list(stroke=c(rep(0.5,8),rep(1,3)),size=c(rep(3,3),rep(5,5),rep(3,3)))))+ggtitle("All Sera")

all.p


DH.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label %in% c("DH","ctr.DH")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="DH"),aes(group="DH",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,3),15,16,17,18,25,9,10,12))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),rep("grey30",3)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3"),
                    breaks=label_order[1:3],
                    label=legend_order[1:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+
  ggtitle("DH Sera")
DH.p


pre.FH.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label%in% c("pre.FH","ctr.pre.FH")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="pre.FH"),aes(group="pre.FH",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,3),15,16,17,18,25,9,10,12))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),rep("grey30",3)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3"),
                    breaks=label_order[1:3],
                    label=legend_order[1:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+
  ggtitle("pre-Farmington Hills Sera")
pre.FH.p



SY.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label %in% c("SY","ctr.SY")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="SY"),aes(group="SY",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,3),15,16,17,18,25,9,10,12))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),rep("grey30",3)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3"),
                    breaks=label_order[1:3],
                    label=legend_order[1:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+
  ggtitle("Sydney Sera")


SY.p




mylegend<-ggpubr::get_legend(all.p)
pre.FH.p<-pre.FH.p+theme(legend.position="none")
DH.p<-DH.p+theme(legend.position="none")
SY.p<-SY.p+theme(legend.position="none")

pre.FH.p+DH.p+SY.p +ggpubr::as_ggplot(mylegend)+ 
  plot_layout(nrow = 1)

ggsave("figure5-dtof.png",width=20,height=10)

fig7B<-all.p

ggsave("figureS7B.png",fig7B,width=12,height=6)

## ---------------------------

## ---------------------------

## independent sera-analysis


# Generating antigen dataframe for plotting

map.preFH <-read.acmap("all-sera-wt-2D.pre.FH.ace")

ag.plot<-data.frame("label"=antigen.list.out,"type"="antigen",
                    "x"=agCoords(map.preFH , 1)[,1],
                    "y"=agCoords(map.preFH , 1)[,2])

# Generating antigen dataframe for plotting, including calculating the mean of the sera


sr.plot<-data.frame("label"="pre.FH","type"="serum",
                    "x"=srCoords(map.preFH ,1)[,1],
                    "y"=srCoords(map.preFH ,1)[,2])

sr.plot<-rbind(sr.plot,
               reshape::cast(reshape2::melt(sr.plot), label ~ variable , mean, margins=TRUE) %>%
                 select(label,x,y) %>%
                 filter(label!="(all)") %>% 
                 mutate(type="serum") %>% 
                 mutate(label=case_when(
                   label=="pre.FH" ~ "ctr.pre.FH"
                 )))

# Merging dataframe of antigen and sera for plotting



ag.sr.plot<-rbind(ag.plot,sr.plot)%>%
  mutate(label=factor(label,levels=c("pre.FH","DH","SY",antigen.list.out,"ctr.pre.FH","ctr.DH","ctr.SY"))) %>%
  mutate(stroke=c(rep(0.5,nrow(ag.plot)+nrow(sr.plot)-3),rep(1.1,3)))



ag.sr.plot$x<--ag.sr.plot$x
ag.sr.plot$y<--ag.sr.plot$y
# Generating aesthetic variables for plotting
label_order<-c("pre.FH","DH","SY",antigen.list.out,"ctr.pre.FH","ctr.DH","ctr.SY")
legend_order<-c("pre-Farmington Hills Sera","Den Haag Sera ","Sydney Sera","US95/95","Farmington Hills 2002",
                "Den Haag 2006","New Orleans 2009","Sydney 2012","Mean pre-Farmington Hills Sera","Den Haag Sera","Sydney Sera")
coord.min=floor(min(c(ag.sr.plot$x,ag.sr.plot$y)))-1
coord.max=ceiling(max(c(ag.sr.plot$x,ag.sr.plot$y)))+1


# begin plotting

all.p1.encircle<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=3)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label %in% c("pre.FH","ctr.pre.FH")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="pre.FH"),
                       aes(group="pre.FH",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,3),15,16,17,18,25,9,10,12))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),rep("grey30",3)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3"),
                    breaks=label_order[1:3],
                    label=legend_order[1:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+guides(color=guide_legend(override.aes = list(stroke=c(rep(0.5,6),rep(1,1)),size=c(rep(3,1),rep(5,5),rep(3,1)))))+
  ggtitle("pre-Farmington Hills Sera")

all.p1.encircle


# DH ----------------------------------------------------------------------


map.DH<-read.acmap("all-sera-wt-2D.DH.ace")

ag.plot<-data.frame("label"=antigen.list.out,"type"="antigen",
                    "x"=agCoords(map.DH, 1)[,1],
                    "y"=agCoords(map.DH, 1)[,2])

# Generating antigen dataframe for plotting, including calculating the mean of the sera


sr.plot<-data.frame("label"="DH","type"="serum",
                    "x"=srCoords(map.DH,1)[,1],
                    "y"=srCoords(map.DH,1)[,2])

sr.plot<-rbind(sr.plot,
               reshape::cast(reshape2::melt(sr.plot), label ~ variable , mean, margins=TRUE) %>%
                 select(label,x,y) %>%
                 filter(label!="(all)") %>% 
                 mutate(type="serum") %>% 
                 mutate(label=case_when(
                   label=="DH" ~ "ctr.DH"
                 )))

# Merging dataframe of antigen and sera for plotting



ag.sr.plot<-rbind(ag.plot,sr.plot)%>%
  mutate(label=factor(label,levels=c("pre.FH","DH","SY",antigen.list.out,"ctr.pre.FH","ctr.DH","ctr.SY"))) %>%
  mutate(stroke=c(rep(0.5,nrow(ag.plot)+nrow(sr.plot)-3),rep(1.1,3)))



ag.sr.plot$x<--ag.sr.plot$x
ag.sr.plot$y<--ag.sr.plot$y
# Generating aesthetic variables for plotting
label_order<-c("pre.FH","DH","SY",rownames(titer_table),"ctr.pre.FH","ctr.DH","ctr.SY")
legend_order<-c("pre-Farmington Hills Sera","Den Haag Sera ","Sydney Sera",rownames(titer_table),"Mean pre-Farmington Hills Sera","Den Haag Sera","Sydney Sera")
# coord.min=floor(min(c(ag.sr.plot$x,ag.sr.plot$y)))-1
# coord.max=ceiling(max(c(ag.sr.plot$x,ag.sr.plot$y)))+1


# begin plotting


all.p2.encircle<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=3)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label %in% c("DH","ctr.DH")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="DH"),aes(group="DH",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,3),15,16,17,18,25,9,10,12))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),rep("grey30",3)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3"),
                    breaks=label_order[1:3],
                    label=legend_order[1:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+guides(color=guide_legend(override.aes = list(stroke=c(rep(0.5,6),rep(1,1)),size=c(rep(3,1),rep(5,5),rep(3,1)))))+
  ggtitle("Den Haag Sera")

all.p2.encircle



# Generating antigen dataframe for plotting

map.SY<-read.acmap("all-sera-wt-2D.SY.ace")

ag.plot<-data.frame("label"=antigen.list.out,"type"="antigen",
                    "x"=agCoords(map.SY, 1)[,1],
                    "y"=agCoords(map.SY, 1)[,2])

# Generating antigen dataframe for plotting, including calculating the mean of the sera


sr.plot<-data.frame("label"="SY","type"="serum",
                    "x"=srCoords(map.SY,1)[,1],
                    "y"=srCoords(map.SY,1)[,2])

sr.plot<-rbind(sr.plot,
               reshape::cast(reshape2::melt(sr.plot), label ~ variable , mean, margins=TRUE) %>%
                 select(label,x,y) %>%
                 filter(label!="(all)") %>% 
                 mutate(type="serum") %>% 
                 mutate(label=case_when(
                   label=="SY" ~ "ctr.SY"
                 )))

# Merging dataframe of antigen and sera for plotting


ag.sr.plot<-rbind(ag.plot,sr.plot)%>%
  mutate(label=factor(label,levels=c("pre.FH","DH","SY",antigen.list.out,"ctr.pre.FH","ctr.DH","ctr.SY"))) %>%
  mutate(stroke=c(rep(0.5,nrow(ag.plot)+nrow(sr.plot)-3),rep(1.1,3)))


ag.sr.plot$x<--ag.sr.plot$x
ag.sr.plot$y<--ag.sr.plot$y
# Generating aesthetic variables for plotting
label_order<-c("pre.FH","DH","SY",rownames(titer_table),"ctr.pre.FH","ctr.DH","ctr.SY")
legend_order<-c("pre-Farmington Hills Sera","Den Haag Sera ","Sydney Sera","US95/95","Farmington Hills 2002",
                "Den Haag 2006","New Orleans 2009","Sydney 2012","Mean pre-Farmington Hills Sera","Den Haag Sera","Sydney Sera")
# coord.min=floor(min(c(ag.sr.plot$x,ag.sr.plot$y)))-1
# coord.max=ceiling(max(c(ag.sr.plot$x,ag.sr.plot$y)))+1



# begin plotting

all.p3.encircle<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=3)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label %in% c("SY","ctr.SY")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggalt::geom_encircle(data=ag.sr.plot %>% filter(type=="serum" & label=="SY"),aes(group="SY",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(rep(20,3),15,16,17,18,25,9,10,12))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),rep("grey30",3)))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3"),
                    breaks=label_order[1:3],
                    label=legend_order[1:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+guides(color=guide_legend(override.aes = list(stroke=c(rep(0.5,6),rep(1,1)),size=c(rep(3,1),rep(5,5),rep(3,1)))))+
  ggtitle("Sydney Sera")

all.p3.encircle


all.p1.encircle<-all.p1.encircle+theme(legend.position="none")
all.p2.encircle<-all.p2.encircle+theme(legend.position="none")
all.p3.encircle<-all.p3.encircle+theme(legend.position="none")


figS8B<-all.p1.encircle+all.p2.encircle+all.p3.encircle+ggpubr::as_ggplot(mylegend)+ 
  plot_layout(nrow = 1)

ggsave("figureS8B.png",figS8B,width=12,height=6)


## ---------------------------

## Comparing 2D map.out and 3D regression of normalised titer data


corr.dat.out.2D<-data.frame("dij"=as.vector(as.matrix(pdist(agBaseCoords(map.out),srBaseCoords(map.out)))),"Dij"=as.numeric(as.vector(tableDistances(map.out))))

corr.plot.out.2D<-ggplot(corr.dat.out.2D,aes(x=Dij,y=dij))+geom_point()+
  theme_bw()+
  scale_x_continuous(expand=c(0,0),limits=c(0,9),breaks=(0:9))+
  scale_y_continuous(expand=c(0,0),limits=c(0,6))+
  coord_fixed()+geom_text(x=7,y=1,label=lm_eqn(corr.dat.out.2D),parse=TRUE)+
  ggtitle("2D Antigenic Map")+xlab(bquote(D[ij]))+ylab(bquote(d[ij]))


corr.dat.out.3D<-data.frame("dij"=as.vector(as.matrix(pdist(agBaseCoords(map3d.out),srBaseCoords(map3d.out)))),"Dij"=as.numeric(as.vector(tableDistances(map3d.out))))

corr.plot.out.3D<-ggplot(corr.dat.out.3D,aes(x=Dij,y=dij))+geom_point()+
  theme_bw()+
  scale_x_continuous(expand=c(0,0),limits=c(0,9),breaks=(0:9))+
  scale_y_continuous(expand=c(0,0),limits=c(0,6))+
  coord_fixed()+geom_text(x=7,y=1,label=lm_eqn(corr.dat.out.3D),parse=TRUE)+
  ggtitle("3D Antigenic Map")+xlab(bquote(D[ij]))+ylab(bquote(d[ij]))

corr.plot.out.2D+corr.plot.out.3D

ggsave("figureS9B.png",corr.plot.out.2D+corr.plot.out.3D)


