## ---------------------------
##
## Script name: Antigenic Cartography for Norovirus
##
## Purpose of script: This script takes coordinate data generated by racmacs from blockade titer data 
## found in XX.
##
## Author: F.A.T.Boshier
##
## Date Created: 2021-10-21
##
## Email: f.boshier@ucl.ac.uk
##
## ---------------------------
##
## Notes:
##   
##
## ---------------------------

## set working directory for Mac and PC

setwd("~/WT_Norovirus/antigenic-cartography")      # Tim's working directory (mac)

## ---------------------------

## load up the packages we will need:  (uncomment as required)
require(Racmacs)
require(ggplot2)
require(tidyverse)
require(knitr)
require(RColorBrewer)
require(wesanderson)
require(viridis)
require(pdist)
require(kableExtra)
require(patchwork)
require(rstatix)

## ---------------------------

## load up our functions into memory

source("functions/plot_acmap3js_all.R") 

## ---------------------------


## ---------------------------

## read in maps generated by racmacs

map<- read.acmap("./all-sera-wt-2D.ace")
map3D<- read.acmap("./all-sera-wt-3D.ace")

antigen.list<-c("Hong_Kong_2019","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008")

## ---------------------------


## ---------------------------

## plot 2D antigenic space - figures 4 D-F


# Generating antigen dataframe for plotting

ag.plot<-data.frame("label"=rownames(titer_table),"type"="antigen",
                    "x"=agCoords(map, 1)[,1],
                    "y"=agCoords(map, 1)[,2])

# Generating antigen dataframe for plotting, including calculating the mean of the sera


sr.plot<-rbind(data.frame("label"="child.1214","type"="serum",
                          "x"=srCoords(map,1)[20:53,1],
                          "y"=srCoords(map,1)[20:53,2]),
               data.frame("label"="adult.1214","type"="serum",
                          "x"=srCoords(map,1)[54:78,1],
                          "y"=srCoords(map,1)[54:78,2]),
               data.frame("label"="adult.1719","type"="serum",
                          "x"=srCoords(map,1)[1:19,1],
                          "y"=srCoords(map,1)[1:19,2])
)

sr.plot<-rbind(sr.plot,
               reshape::cast(reshape2::melt(sr.plot), label ~ variable , mean, margins=TRUE) %>%
                 select(label,x,y) %>%
                 filter(label!="(all)") %>% 
                 mutate(type="serum") %>% 
                 mutate(label=case_when(
                   label=="child.1214" ~ "ctr.child1214",
                   label=="adult.1214" ~ "ctr.adult1214",
                   label=="adult.1719" ~ "ctr.adult1719",
                 )))

# Merging dataframe of antigen and sera for plotting

ag.sr.plot<-rbind(ag.plot,sr.plot)%>%
  mutate(label=factor(label,levels=c("child.1214","adult.1214","adult.1719","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719"))) %>%
  mutate(stroke=c(rep(0.5,83),rep(1.1,3)))

ag.sr.plot$x<--ag.sr.plot$x
ag.sr.plot$y<--ag.sr.plot$y
# Generating aesthetic variables for plotting
label_order<-c("child.1214","adult.1214","adult.1719","Sydney_2012","Den_Haag_2006","Den_Haag_2017","Osaka_2008","Hong_Kong_2019","ctr.child1214","ctr.adult1214","ctr.adult1719")
legend_order<-c("2013-2014 Children's Sera ","2013-2014 Adult's Sera ","2017-2019 Adult's Sera",
                "Sydney 2012 Isolate","Den_Haag 2006 Isolate","Den Haag_2017 Isolate","Osaka 2008 Isolate","Hong Kong 2019 Isolate","Mean 2013-2014 Children's Sera","Mean 2013-2014 Adult's Sera","Mean 2017-2019 Adult's Sera")
coord.min=floor(min(c(ag.sr.plot$x,ag.sr.plot$y)))-1
coord.max=ceiling(max(c(ag.sr.plot$x,ag.sr.plot$y)))+1

# begin plotting

all.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label,stroke=stroke),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum"),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggforce::geom_mark_ellipse(data=ag.sr.plot %>% filter(type=="serum" & label=="adult.1214"),aes(group="adult.1214",fill=label),color=NA,alpha=1/4)+
  ggforce::geom_mark_ellipse(data=ag.sr.plot %>% filter(type=="serum" & label=="adult.1719"),aes(group="adult.1719",fill=label),color=NA,alpha=1/4)+
  ggforce::geom_mark_ellipse(data=ag.sr.plot %>% filter(type=="serum" & label=="child.1214"),aes(group="child.1214",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(3,4,8,15,16,17,18,25,9,10,12))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),"dodgerblue","darkolivegreen4","darkorchid3"))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3"),
                    breaks=label_order[1:3],
                    label=legend_order[1:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+guides(color=guide_legend(override.aes = list(stroke=c(rep(0.5,8),rep(1,3)),size=c(rep(3,3),rep(5,5),rep(3,3)))))+ggtitle("All Sera")


child.1214.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label %in% c("child.1214","ctr.child1214")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggforce::geom_mark_ellipse(data=ag.sr.plot %>% filter(type=="serum" & label=="child.1214"),aes(group="child.1214",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(3,4,8,15,16,17,18,25,9,10,12))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),"dodgerblue","darkolivegreen4","darkorchid3"))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3"),
                    breaks=label_order[1:3],
                    label=legend_order[1:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+
  ggtitle("2013-2014 Children's Sera")


adult.1214.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label%in% c("adult.1214","ctr.adult1214")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggforce::geom_mark_ellipse(data=ag.sr.plot %>% filter(type=="serum" & label=="adult.1214"),aes(group="adult.1214",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(3,4,8,15,16,17,18,25,9,10,12))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),"dodgerblue","darkolivegreen4","darkorchid3"))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3"),
                    breaks=label_order[1:3],
                    label=legend_order[1:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+
  ggtitle("2013-2014 Adult's Sera")



adult.1719.p<-ggplot(ag.sr.plot,aes(x=x,y=y))+geom_point(data=ag.sr.plot %>% filter(type=="antigen"),aes(shape=label,color=label),fill="black",size=5)+
  geom_point(data=ag.sr.plot %>% filter(type=="serum" & label %in% c("adult.1719","ctr.adult1719")),aes(x=x,y=y,color=label,shape=label,stroke=stroke),size=3)+
  ggforce::geom_mark_ellipse(data=ag.sr.plot %>% filter(type=="serum" & label=="adult.1719"),aes(group="adult.1719",fill=label),color=NA,alpha=1/4)+
  scale_shape_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c(3,4,8,15,16,17,18,25,9,10,12))+
  scale_color_manual(name="Data",breaks=label_order,
                     labels=legend_order,
                     values=c("dodgerblue","darkolivegreen4","darkorchid3",rep("black",5),"dodgerblue","darkolivegreen4","darkorchid3"))+
  scale_fill_manual(values=c("dodgerblue","darkolivegreen4","darkorchid3"),
                    breaks=label_order[1:3],
                    label=legend_order[1:3],
                    guide="none")+
  scale_x_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  scale_y_continuous(expand=c(0,0),limits=c(coord.min,coord.max),breaks=c(coord.min:coord.max))+
  theme_bw()+theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank(),
                   panel.grid.minor = element_blank())+
  coord_fixed()+
  ggtitle("2017-2019 Adults Sera")



mylegend<-ggpubr::get_legend(all.p)
child.1214.p<-child.1214.p+theme(legend.position="none")
adult.1214.p<-adult.1214.p+theme(legend.position="none")
adult.1719.p<-adult.1719.p+theme(legend.position="none")

child.1214.p+adult.1214.p + adult.1719.p +ggpubr::as_ggplot(mylegend)+ 
  plot_layout(nrow = 1)

ggsave("figure4-dtof.png",width=12,height=6)

## ---------------------------

## ---------------------------

## plot 3D antigenic space

plot_acmap3js_all(map3d)

## ---------------------------





## ---------------------------

## Comparing 2D map and 3D regression of normalised titer data

lm_eqn <- function(df){
  m <- lm(dij ~ Dij, df);
  eq <- substitute(italic(R)^2~"="~r2, 
                   list(r2 = format(summary(m)$r.squared, digits = 3)))
  as.character(as.expression(eq));
}

corr.dat.2D<-data.frame("dij"=as.vector(as.matrix(pdist(agBaseCoords(map),srBaseCoords(map)))),"Dij"=as.numeric(as.vector(tableDistances(map))))

corr.plot.2D<-ggplot(corr.dat.2D,aes(x=Dij,y=dij))+geom_point()+
  theme_bw()+
  scale_x_continuous(expand=c(0,0),limits=c(0,9),breaks=(0:9))+
  scale_y_continuous(expand=c(0,0),limits=c(0,6))+
  coord_fixed()+geom_text(x=7,y=1,label=lm_eqn(corr.dat),parse=TRUE)+
  ggtitle("2D Antigenic Map")+xlab(bquote(D[ij]))+ylab(bquote(d[ij]))


corr.dat.3D<-data.frame("dij"=as.vector(as.matrix(pdist(agBaseCoords(map3d),srBaseCoords(map3d)))),"Dij"=as.numeric(as.vector(tableDistances(map3d))))

corr.plot.3D<-ggplot(corr.dat.3D,aes(x=Dij,y=dij))+geom_point()+
  theme_bw()+
  scale_x_continuous(expand=c(0,0),limits=c(0,9),breaks=(0:9))+
  scale_y_continuous(expand=c(0,0),limits=c(0,6))+
  coord_fixed()+geom_text(x=7,y=1,label=lm_eqn(corr.dat),parse=TRUE)+
  ggtitle("3D Antigenic Map")+xlab(bquote(D[ij]))+ylab(bquote(d[ij]))

corr.plot.2D+corr.plot.3D

ggsave("supplementary-figure-4.png",corr.plot.2D+corr.plot.3D)

## ---------------------------




## ---------------------------

## Comparing 2D map and 3D regression of normalised titer data

lm_eqn <- function(df){
  m <- lm(dij ~ Dij, df);
  eq <- substitute(italic(R)^2~"="~r2, 
                   list(r2 = format(summary(m)$r.squared, digits = 3)))
  as.character(as.expression(eq));
}

corr.dat.2D<-data.frame("dij"=as.vector(as.matrix(pdist(agBaseCoords(map),srBaseCoords(map)))),"Dij"=as.numeric(as.vector(tableDistances(map))))

corr.plot.2D<-ggplot(corr.dat.2D,aes(x=Dij,y=dij))+geom_point()+
  theme_bw()+
  scale_x_continuous(expand=c(0,0),limits=c(0,9),breaks=(0:9))+
  scale_y_continuous(expand=c(0,0),limits=c(0,6))+
  coord_fixed()+geom_text(x=7,y=1,label=lm_eqn(corr.dat),parse=TRUE)+
  ggtitle("2D Antigenic Map")+xlab(bquote(D[ij]))+ylab(bquote(d[ij]))


corr.dat.3D<-data.frame("dij"=as.vector(as.matrix(pdist(agBaseCoords(map3d),srBaseCoords(map3d)))),"Dij"=as.numeric(as.vector(tableDistances(map3d))))

corr.plot.3D<-ggplot(corr.dat.3D,aes(x=Dij,y=dij))+geom_point()+
  theme_bw()+
  scale_x_continuous(expand=c(0,0),limits=c(0,9),breaks=(0:9))+
  scale_y_continuous(expand=c(0,0),limits=c(0,6))+
  coord_fixed()+geom_text(x=7,y=1,label=lm_eqn(corr.dat),parse=TRUE)+
  ggtitle("3D Antigenic Map")+xlab(bquote(D[ij]))+ylab(bquote(d[ij]))

corr.plot.2D+corr.plot.3D

ggsave("supplementary-figure-4.png",corr.plot.2D+corr.plot.3D)

## ---------------------------





